---
- name: Generate temporary kubeconfig for AWS EKS
  shell: >
    aws eks update-kubeconfig
    --region {{ aws_region }}
    --name {{ cluster_name }}
    --profile {{ aws_profile }}
    --kubeconfig ~/kubeconfig-{{ cluster_name }}
  environment:
    KUBECONFIG: "~/kubeconfig-{{ cluster_name }}"
  args:
    executable: /bin/bash
  register: kubeconfig_result

- name: Display kubeconfig generation result
  debug:
    var: kubeconfig_result.stdout
